### ISSUE TITLE
Problem generating heatmaps on Ubuntu

### ISSUE THREAD

**Issue by StevenWingett** [s-andrews/compter#6]
I tried to quickly put together a GitHub Actions workflow for Compter.  However, it seems that the code below does not work on Ubuntu (I've also tried this on a Virtual Box running Ubuntu).

I could re-write the code to write out an  R script and then run with an "Rscript" system command.  (This would mean running Rscript rather than R).  What do you think?

Thanks,
Steven

Run $GITHUB_WORKSPACE/compter --background mouse --outfile testing.txt $GITHUB_WORKSPACE/test/high_seqs.fa $GITHUB_WORKSPACE/test/low_seqs.fa
Reading background from /home/runner/work/compter/compter/backgrounds/mouse.cmp
Processing /home/runner/work/compter/compter/test/high_seqs.fa
...
Processing /home/runner/work/compter/compter/test/low_seqs.fa
..
Drawing heatmap
Can't write to 'R' pipe  - do you need to set an rpath? at /home/runner/work/compter/compter/compter line 201.
##[error]Process completed with exit code 1.

**Comment by s-andrews** [comment]
It's probbaly just that pheatmap isn't installed in the R environment.

**Comment by StevenWingett** [comment]
This was the problem and has now been fixed.
